config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "museum_objects#index"

  resources :museum_objects, only: [:index, :create, :show], param: :system_number, system_number: /O\d+/ do
    get 'search', on: :collection
    member do
      resources :reflections, shallow: true
    end
  end

  resource :session
  resource :registration
  resource :password_reset
  resource :password

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [:edit, :update]

  def new    
  end

  def create
    if (user = User.find_by(email: params[:email]))
      PasswordMailer.with(
        user: user,
        token: user.generate_token_for(:password_reset)
      ).password_reset.deliver_later
    end

    redirect_to root_path, notice: "Check your inbox for a password reset email."
  end

  def edit
  end

  def update
    if @user.update(password_params)
      redirect_to new_session_path, notice: "Your password has been reset successfully. Please log in.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_token_for(:password_reset, params[:token])
    unless @user.present?
      redirect_to new_password_resets_path, alert: "Invalid token, please request a new password reset email.", status: :see_other
    end
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password, autocomplete: "new-password" %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div>
    <%= form.submit "Reset password" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, autocomplete: "email" %>
  </div>

  <div>
    <%= form.submit "Request password reset"%>
  </div>
<% end %>