config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "museum_objects#index"

  resources :museum_objects, only: [:index, :create, :show], param: :system_number, system_number: /O\d+/ do
    get 'search', on: :collection
    member do
      resources :reflections, shallow: true
    end
  end

  resource :session
  resource :registration
  resource :password_reset
  resource :password

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/reflection.rb
class Reflection < ApplicationRecord
  belongs_to :user
  belongs_to :museum_object

  validates :deaccession_flag, presence: true, inclusion: [true, false]
  validate :at_least_one_text_response_required

  def at_least_one_text_response_required
    text_fields = [deaccession_reason, provenance_thoughts, presence_feelings, absence_feelings]
    if text_fields.all?(&:blank?)
      errors.add :base, :text_response, message: "You must write a response to at least one prompt"
    end
  end
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
  end

  def new
    @museum_object = MuseumObject.find_by!(system_number: params[:system_number])
    @vanda_object = VandaCollection::Wrapper.find_by_system_number(params[:system_number])
    @reflection = @museum_object.reflections.new
  end

  def create
    @museum_object = MuseumObject.find_by!(system_number: params[:system_number])
    @vanda_object = VandaCollection::Wrapper.find_by_system_number(params[:system_number])
    @reflection = @museum_object.reflections.new(reflection_params)
    @reflection.update(user_id: current_user.id)

    if @reflection.save
      redirect_to @reflection, notice: "Reflection saved successfully!"
    else
      flash.now[:alert] = "Reflection could not be saved."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @reflection = Reflection.find(params[:id])
    @user = User.find(@reflection.user_id)
    @museum_object = MuseumObject.find(@reflection.museum_object_id)
    @vanda_object = VandaCollection::Wrapper.find_by_system_number(@museum_object.system_number)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def reflection_params
    params.require(:reflection).permit(
      :deaccession_flag,
      :deaccession_reason,
      :provenance_thoughts,
      :presence_feelings,
      :absence_feelings
    )
  end
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
end

app/views/reflections/create.html.erb
<h1>Reflections#create</h1>
<p>Find me in app/views/reflections/create.html.erb</p>

app/views/reflections/destroy.html.erb
<h1>Reflections#destroy</h1>
<p>Find me in app/views/reflections/destroy.html.erb</p>

app/views/reflections/edit.html.erb
<h1>Reflections#edit</h1>
<p>Find me in app/views/reflections/edit.html.erb</p>

app/views/reflections/index.html.erb
<h1>Reflections#index</h1>
<p>Find me in app/views/reflections/index.html.erb</p>

app/views/reflections/new.html.erb
<h1>Write a reflection</h1>

<%= form_with model: [@museum_object, @museum_object.reflections.build ], url: reflections_path do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <%= field_set_tag "Flag this object for deaccession?" do %>
    <%= form.radio_button :deaccession_flag, true, checked: true %>
    <%= form.label :deaccession_flag_true, "Yes" %>
    <%= form.radio_button :deaccession_flag, false %>
    <%= form.label :deaccession_flag_false, "No" %>
  <% end %>

  <%= form.label :deaccession_reason, "If yes, why do you think it should leave the collection?" %> <br>
  <%= form.text_area :deaccession_reason %> <br>

  <%= form.label :provenance_thoughts, "What do you think about this object's provenance?" %> <br>
  <%= form.text_area :provenance_thoughts %> <br>

  <%= form.label :presence_feelings, "How do you feel about this object's presence in the collection?" %> <br>
  <%= form.text_area :presence_feelings %> <br>

  <%= form.label :absence_feelings, "How would you feel about this object leaving the collection?" %> <br>
  <%= form.text_area :absence_feelings %> <br>

  <%= form.submit "Save"%>
<% end %>

<%= render "museum_objects/vanda_object" %>

app/views/reflections/show.html.erb
<h1>A reflection by <%= @user.name %> on <%= @museum_object.name %></h1>

<h3> <%= @reflection.deaccession_flag ? "Flagged" : "Not flagged" %> for deaccession from the collection </h3>

<dl>
  <% if @reflection.deaccession_reason.present? %>
    <dt>Why do you think it should leave the collection?</dt>
    <dd>
      <%= @reflection.deaccession_reason %>
    </dd>
  <% end %>

  <% if @reflection.provenance_thoughts.present? %>
    <dt>What do you think about this object's provenance?</dt>
    <dd>
      <%= @reflection.provenance_thoughts %>
    </dd>
  <% end %>

  <% if @reflection.presence_feelings.present? %>
    <dt>How do you feel about this object's presence in the collection?</dt>
    <dd>
      <%= @reflection.presence_feelings %>
    </dd>
  <% end %>

  <% if @reflection.absence_feelings.present? %>
    <dt>How would you feel about this object leaving the collection?</dt>
    <dd>
      <%= @reflection.absence_feelings %>
    </dd>
  <% end %>
</dl>

<%= render "museum_objects/vanda_object" %>

app/views/reflections/update.html.erb
<h1>Reflections#update</h1>
<p>Find me in app/views/reflections/update.html.erb</p>