config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "museum_objects#index"

  resources :museum_objects, only: [:index, :create, :show], param: :system_number, system_number: /O\d+/ do
    get 'search', on: :collection
    member do
      resources :reflections, shallow: true
    end
  end

  resource :session
  resource :registration
  resource :password_reset
  resource :password

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to("Home", root_path, aria: { current: (current_page?(root_path) ? "page" : nil) }) %>
    </li>
    <% if user_signed_in? %>
      <li>
        <%= link_to("Edit password", edit_password_path, aria: { current: (current_page?(edit_password_path) ? "page" : nil) }) %>
      </li>
      <li>
        <%= button_to "Log out", session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to("Sign up", new_registration_path, aria: { current: (current_page?(new_registration_path) ? "page" : nil) }) %>
      </li>
      <li>
        <%= link_to("Log in", new_session_path, aria: { current: (current_page?(new_session_path) ? "page" : nil) }) %>
      </li>
    <% end %>
  </ul>
</nav>