config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "museum_objects#index"

  resources :museum_objects, only: [:index, :create, :show], param: :system_number, system_number: /O\d+/ do
    get 'search', on: :collection
    member do
      resources :reflections, shallow: true
    end
  end

  resource :session
  resource :registration
  resource :password_reset
  resource :password

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/museum_object.rb
class MuseumObject < ApplicationRecord
  has_many :reflections
  has_many :users, through: :reflections

  validates :system_number, presence: true, uniqueness: true, format: { with: /\AO\d+\z/ , message: "must be in correct format"}
  validates :name, presence: true
end

app/controllers/museum_objects_controller.rb
class MuseumObjectsController < ApplicationController
  def index
    @museum_objects = MuseumObject.all
  end

  def show
    @museum_object = MuseumObject.find_by!(system_number: params[:system_number])

    @vanda_object = VandaCollection::Wrapper.find_by_system_number(@museum_object.system_number)
    unless @vanda_object
      @museum_objects = MuseumObject.all
      flash.now[:alert] = "Object not found"
      render :index, status: :not_found
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "Object not found"
  end

  def search
    @museum_object = MuseumObject.new

    @vanda_object = VandaCollection::Wrapper.find_by_system_number(params[:system_number])
    unless @vanda_object
      @museum_objects = MuseumObject.all
      flash.now[:alert] = "Object not found"
      render :index, status: :not_found
    end
  end

  def create
    @museum_object = MuseumObject.new(museum_object_params)
    # Assign MuseumObject a name from the API result primary title or object type if no title.
    # Will throw error if system number invalid, which devalues subsequent control flow.
    # TODO: integrate this into forthcoming Service
    vanda_object = VandaCollection::Wrapper.find_by_system_number(@museum_object.system_number)
    object_name = vanda_object.record.titles[0].title.presence || vanda_object.record.object_type
    @museum_object.update(name: object_name)

    if @museum_object.save
      redirect_to museum_object_path(@museum_object.system_number), notice: "Object saved successfully"
    else
      @vanda_object = VandaCollection::Wrapper.find_by_system_number(params[:museum_object][:system_number])
      unless @vanda_object
        flash[:alert] = "Object could not be saved"
        redirect_back(fallback_location: root_path)
        return
      end
      flash.now[:alert] = "Object could not be saved"
      render :search, status: :unprocessable_entity
    end
  end

  private

  def museum_object_params
    params.require(:museum_object).permit(:system_number)
  end
end

app/helpers/museum_objects_helper.rb
module MuseumObjectsHelper
end

app/views/museum_objects/_vanda_object.html.erb
<h2><%= @vanda_object.record.titles.present? ? @vanda_object.record.titles[0].title : @vanda_object.record.object_type %></h2>

<% if @vanda_object.meta.images.present? %>
  <%= image_tag(@vanda_object.meta.images._primary_thumbnail, alt: "#{} thumbnail") %>
<% end %>

<h3>Object details</h3>
<dl>
  <dt>Date</dt>
  <dd>
    <%= @vanda_object.record.production_dates.present? ? "#{@vanda_object.record.production_dates[0].date.text} (#{@vanda_object.record.production_dates[0].association.text})" : "Unknown" %>
  </dd>

  <dt>Artist/Maker</dt>
  <dd>
    <%= @vanda_object.record.artist_maker_person.present? ? @vanda_object.record.artist_maker_person[0].name.text : "Unknown" %>
  </dd>

  <% if @vanda_object.record.places_of_origin.present? %>
    <dt>Place of origin</dt>
    <dd>
        <% @vanda_object.record.places_of_origin.each do |p| %>
          <%= "#{p.place.text} (#{p.association.text})" %>
        <% end %>
    </dd>
  <% end %>

  <dt>System number</dt>
  <dd>
    <%= @vanda_object.record.system_number %>
  </dd>

  <dt>Object type</dt>
  <dd>
    <%= @vanda_object.record.object_type %>
  </dd>

  <% if @vanda_object.record.titles.present? %>
    <dt>Title(s)</dt>
    <dd>
      <% @vanda_object.record.titles.each do |t| %>
        <%= "#{t.title} (#{t.type})" %>
      <% end %>
    </dd>
  <% end %>

  <% if @vanda_object.record.brief_description.present? %>
    <dt>Brief description</dt>
    <dd>
      <%= sanitize @vanda_object.record.brief_description %>
    </dd>
  <% end %>

  <dt>Materials and techniques</dt>
  <dd>
    <%= @vanda_object.record.materials_and_techniques %>
  </dd>

  <% if @vanda_object.record.physical_description.present? %>
    <dt>Physical description</dt>
    <dd>
      <%= sanitize @vanda_object.record.physical_description %>
    </dd>
  <% end %>

  <% if @vanda_object.record.summary_description.present? %>
    <dt>Summary</dt>
    <dd>
      <%= sanitize @vanda_object.record.summary_description %>
    </dd>
  <% end %>

  <% if @vanda_object.record.object_history.present? %>
    <dt>Object history</dt>
    <dd>
      <%= sanitize @vanda_object.record.object_history %>
    </dd>
  <% end %>

  <% if @vanda_object.record.historical_context.present? %>
    <dt>Historical context</dt>
    <dd>
      <%= sanitize @vanda_object.record.historical_context %>
    </dd>
  <% end %>

  <% if @vanda_object.record.associated_events.present? %>
    <dt>Associated events</dt>
    <dd>
        <% @vanda_object.record.associated_events.each do |event| %>
          <%= sanitize event.text %>
        <% end %>
    </dd>
  <% end %>

  <% if @vanda_object.record.gallery_labels.present? %>
    <dt>Most recent gallery label</dt>
    <dd>
      <%= sanitize @vanda_object.record.gallery_labels[0].text %> <br>
      <%= sanitize @vanda_object.record.gallery_labels[0].date.text %>
    </dd>
  <% end %>
</dl>

app/views/museum_objects/index.html.erb
<h1>Contested Objects</h1>

<h2>Search the V&A Collection for a museum object</h2>
<%= form_with url: search_museum_objects_path, method: :get do |form| %>
  <%= form.label :system_number, "Search by system number:" %>
  <%= form.text_field :system_number %>
  <%= form.submit "Search", name: nil %>
<% end %>

<h2>Saved museum objects</h2>
<ul>
  <% @museum_objects.each do |museum_object| %>
  <li>
    <%= link_to museum_object.system_number, museum_object_path(museum_object.system_number) %>
  </li>
  <% end %>
</ul>

app/views/museum_objects/search.html.erb
<h1>Search result</h1>

<%= form_with model: @museum_object, url: museum_objects_path, method: :post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <%= form.hidden_field :system_number, value: @vanda_object.record.system_number %>
  <%= form.submit "Save this object" %>
<% end %>

<%= render "vanda_object" %>

app/views/museum_objects/show.html.erb
<%= render "vanda_object" %>